name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check environment
        run: echo "VITE_APP_BD=$VITE_APP_BD"
        env:
          VITE_APP_BD: ${{ vars.VITE_APP_BD }}

      - name: Build
        run: npm run build
        env:
          VITE_APP_MAP_API: ${{ vars.VITE_APP_MAP_API }}
          VITE_APP_MAPTILER_API: ${{ vars.VITE_APP_MAPTILER_API }}
          VITE_APP_MERCATOR: ${{ vars.VITE_APP_MERCATOR }}
          VITE_APP_BD: ${{ vars.VITE_APP_BD }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
